# Generated by Django 3.1.3 on 2020-11-28 16:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
