# Generated by Django 3.1.3 on 2020-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0002_auto_20201128_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('RU', 'rus'), ('EN', 'eng'), ('TU', 'tur')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
