# Generated by Django 3.1.3 on 2020-11-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0003_auto_20201128_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
