# Generated by Django 3.1.3 on 2020-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0004_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_for_but',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], max_length=10),
        ),
    ]
